services:
  evdealersales.webmvc:
    build:
      context: .
      dockerfile: EVDealerSales/Dockerfile
    image: evdealersales-webmvc:latest
    depends_on:
      - evdealersales.database
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=localhost,1433;Database=EVDealerSalesDb;User Id=sa;Password=StrongP@ssw0rd!;TrustServerCertificate=True;Encrypt=False;MultipleActiveResultSets=True
      - "JWT__SecretKey=EVDealerSales_SECRETKEY_SIEUCAPBAOMAT_VAYMACHUADU16KYTU"
      - "JWT__Issuer=EVDealerSales_Issuer"
      - "JWT__Audience=EVDealerSales_Audience" 
    ports:
      - "5000:8080"

  evdealersales.database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: evdealersales-sqlserver
    environment:
      SA_PASSWORD: "StrongP@ssw0rd!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data:
   driver: local
